version: 1.0

debug: false

# should we generate blocks even if player is offline ?
offlineGenerator: true

autoSave: true
autoSave-Period: 1800 # seconds

feedEnergySystem:
  enable: true

# ranks - permission based
generatorAmount:
  default: 5
  astra: 6
  nova: 7
  supernova: 9
  galaxy: 11
  sponsor: 14
